### PR TITLE
Arch makepkg fix

### PR DESCRIPTION
**Pull request by Zoogsz**
Fixed and working makepkg for arch. 
Literally just had an outdated source URL
[pkgbuild.txt](https://github.com/oxen-io/lokinet/files/9277791/pkgbuild.txt)

### CODE REVIEW

**Comment by majestrate** [comment]
build the `makepkg` branch, not the `dev` branch for arch linux package.

**Comment by demostanis** [comment]
literally doesn't build anymore for me due to oxenmq linking errors, but why did you force push? i can't tell makepkg to use `1e1b3e5` commit (which was working) anymore...

**Comment by majestrate** [comment]
alright, i'll reset it back to the contents of that commit and rebase

**Comment by majestrate** [comment]
that commit is waaaaaaaaaaayyy too old to revert back to.

**Comment by demostanis** [comment]
don't revert, but at least get it back in the history so that i can use it

**Pull request closed without merging**
