### PR TITLE
use libuv threadpool instead of oxenmq's threadpool.

### PR DESCRIPTION
**Pull request by majestrate**
add EventLoop work pure virtual method for doing threaded work on the event loop.

switch over libuv to provide work via their threadpool.

### CODE REVIEW

**Comment by majestrate** [comment]
this had the cost of 1 file handle per job which is no bueno

**Comment by majestrate** [comment]
On Sun, 08 May 2022 06:15:53 -0700
majestrate ***@***.***> wrote:

> this had the cost of 1 file handle per job which is no bueno
> 
> 

i am pretty sure i need to revisit how we do threaded work, probably
adding a concept for batching.

**Comment by jagerman** [comment]
I'm not sure about Windows (and that might be worth investigating), but on Linux (and I'd expect macos and pretty much anything else unix-like) oxenmq's job scheduling has noticeably less overhead per job than a traditional thread pool because it avoids any mutex lock contention between worker threads looking for jobs (it is instead all using inproc sockets to get job info from the master thread to worker threads).

**Comment by jagerman** [comment]
Though a filehandler per job seems like pretty big overhead even compared to a traditional mutex-locking thread queue.

**Pull request closed without merging**
