### PR TITLE
issue 1700: ICMP Packet too big

### PR DESCRIPTION
**Pull request by majestrate**
rewrite checksums on icmp destination unreachable packets including inner ip header and following tomfoolery

### CODE REVIEW

**Comment by majestrate** [comment]
@neilalexander let me know if this fixes #1700

**Comment by neilalexander** [comment]
I'll try to check this over the weekend!

**Comment by jagerman** [comment]
> I'll try to check this over the weekend!

@neilalexander Any update?

**Comment by neilalexander** [comment]
@jagerman Did a bit of testing with @majestrate today and although the inner headers are seemingly rewritten properly by this PR, the checksums are still off, so will await further poking for additional testing.

**Comment by majestrate** [comment]
i am going to close this pr and use a branch with this year in it so i can delete all my branches from 2021

**Pull request closed without merging**
