### PR TITLE
Fix inbound IP handling; update [bind] docs

### LINKED ISSUE #1929: Binding to wrong IP
On a service node I have the following config (irrelevant bits of config snipped):
```
[router]
public-ip=149.56.165.112
public-port=10909
[bind]
0.0.0.0=10909
```
but the lokinet's open udp ports end up as:
```
udp        0      0 51.79.20.22:10909       0.0.0.0:*                           1138933/lokinet     
udp        0      0 127.109.0.0:53          0.0.0.0:*                           1138933/lokinet     
udp        0      0 149.56.165.112:41937    0.0.0.0:*                           1138933/lokinet     
```
but this isn't exhibiting the right behaviour: the *output* IP is correctly bound to the public-ip, but the inbound IP looks like it is using the first IP listed on the interface rather than `public-ip`.

The intended behaviour here was to fail in such a case -- i.e. I have more than one IP, and didn't specify one in the `[bind]` section, but it isn't failing: lokinet is starting and apparently just using the first address on the interface.  (The result is an unreachable lokinet, because 149.56.165.112 is the default source IP, but that doesn't work right when we reply to something that we received on 51.x).

I think we need to split up this configuration better, and make the behaviour a little more obvious:

- add new options `incoming=1.2.3.4:1090` and `outgoing=5.6.7.8:1099` options to the `[bind]` section, and make this the only non-deprecated way to specify IPs.  We should probably allow `incoming=:1090` as an alias for `0.0.0.0:1090`
- we likely need to allow multiple `incoming` addresses, probably not `outgoing`.
- for future use, we'll likely want some other keys here (e.g. `quic-in=`, `quic-out=`).
- if you bind to IP 0.0.0.0 (either with the new, or the deprecated, interface, or using a new `:1090` value) then:
  - if we have a `public-ip` given in the `[router]` section and that IP exists on the system, bind to it for both incoming/outgoing IPs.
  - otherwise go looking for a unique public IP and, if we find one (and only one), bind to that.
  - if we find more than one public IP (or no public IP), die with a message that you need to list a specific IP in the `[bind]` section.
- deprecate specifying interface names.  They are non-portable across machines, and also don't uniquely identify an IP (i.e. one interface can have multiple IPs).

### PR DESCRIPTION
**Pull request by jagerman**
- Fixes #1929 issue with `inbound=:1234` not defaulting to an auto-detected public IP
- Updates/rearranges some `[bind]` section config documentation

### CODE REVIEW

**Comment by majestrate** [comment]
Outbound links should NOT use wildcard, that is the original bug that was being fixed here. Outbound listen ip matches any inbound listen ip.

**Comment by jagerman** [comment]
> Outbound links should NOT use wildcard

This is not at all what was implemented in #1930, either in the config descriptions or the code.  The config says it defaults to wildcard, and indeed if you don't have any outbound at all, it defaults to wildcard.

**Comment by jagerman** [comment]
I vaguely recall that we had a conversation about this a couple weeks ago, and decided it was probably still okay to use a wildcard for outgoing because, since we are the initiator, we ought to end up using a consistent source IP address anyway.

**Comment by majestrate** [comment]
The issue was on boxes with multiple ip per interface wildcard did not always choose source correctly so we decided to match the listen ip on both inbound and outbound to make sure it does

**Comment by jagerman** [comment]
> The issue was on boxes with multiple ip per interface wildcard did not always choose source correctly so we decided to match the listen ip on both inbound and outbound to make sure it does

The main issue was with incoming: if I'm listening on 1.2.3.4:5678, but my default source address is 1.2.3.5 then my reply to a packet sent to that 1.2.3.4 address will have unexpected source address 1.2.3.5, which caused problems at the other end.

For outbound, it's less clear to me that the same issue exists: I'm going to send a packet to some remote, the system will put the 1.2.3.5 source address on it, and that packet goes out.  A response to that packet directed at 1.2.3.5 will reach me and I'll be fine with it, and if I respond to *that* one, it ought to still use the 1.2.3.5 address, since that's my default routing IP.

**Comment by jagerman** [comment]
(It's also rather unclear to me how a lokinet client, typically behind NAT, could reasonably have anything other than a wildcard default).

**Review by majestrate — APPROVED** [review]

**Pull request merged**
