### PR TITLE
[WIP] New win32 route manager

### PR DESCRIPTION
**Pull request by majestrate**
attempts to plug a ipv6 route leak on windows

### CODE REVIEW

**Comment by majestrate** [comment]
rebased

**Comment by majestrate** [comment]
note to self, squash commits.

**Comment by despair86** [comment]
tested this branch on aws box, disabled ip6 on that interface using powershell
```
PS C:\> Disable-NetAdapterBinding -Name lokitun0 -ComponentID ms_tcpip6
```
this may have fixed that ip6 leak, could add this command to the installer if it has the ability to shell out to ps

**Comment by majestrate** [comment]
replaced by #1899
i hate windows so god damn much

**Pull request closed without merging**
